wml_credentials:
  # Option 1) username and password
  username: jbtang@au1.ibm.com
  password: yourpassword

  # Option 2) using access_token instead of username/password
  # how to generate access_token, refer to:
  # CPD3.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/3.5.0?topic=overview-authentication
  # CPD4.0: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=resources-generating-authorization-token
  # CPD4.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=resources-generating-authorization-token-api-key
  # Also in CPD Watson Studio, simply run: user_token = os.environ["USER_ACCESS_TOKEN"]
  # "token": user_token

  # option 3) using apikey instead of username/password
  # how to generate apikey, refer to:
  # CPD3.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/3.5.0?topic=started-generating-api-keys#api-keys__platform
  # CPD4.0: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=steps-generating-api-keys
  # CPD4.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=steps-generating-api-keys
  # "apikey": api_key

  instance_id: openshift
  url: https://dse-cpd45-cluster1.cpolab.ibm.com/
  version: '4.5'

prj_info:
  code_dir: ../code_example_to_be_deployed
  main_file: main_no_email.py

deployment_info:
  # self-defined function name
  function_name: code_example_to_be_deployed

  # how to create deployment space, refer to:
  # CPD3.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/3.5.0?topic=functions-deployment-spaces#create
  # CPD4.0: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=spaces-creating-deployment
  # CPD4.5: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.5.x?topic=spaces-creating-deployment
  space_id: fb22386d-ec8e-4b60-a6a6-52651f9c0960

  # True: replace deployment if same deployment name has been found
  # False: quit the deployment if same deployment name has been found
  force_2_update: True   # default value: False

  # 2 different deploy_modes:
  # online: online API
  # batch_job: scheduled upon requests
  deploy_mode: batch_job  # default value: batch_job

  # hardware spec: refer to:https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/deploy-batch-details.html
  # Size 	Hardware definition
  # XS 	1 CPU and 4 GB RAM
  # S 	2 CPU and 8 GB RAM
  # M 	4 CPU and 16 GB RAM
  # ML 	4 CPU and 32 GB RAM
  # L 	8 CPU and 32 GB RAM
  # XL 	16 CPU and 64 GB RAM
  hardware_spec: S

  # enable scalability when multiple nodes are needed
  num_nodes: 1

  # Define runtime. Must have '' in the string.
  # For cpd3.5, it can be: 'default_py3.7'
  # For cpd4.x, it can be: 'runtime-22.1-py3.9'
  runtime: 'runtime-22.1-py3.9'

#  If no smtp email function, please either comment out whole below section,
#  or set "False" to "send_email_when_successful" and "send_email_when_fail"
email_setting:
  send_email_when_successful: True # True, False. Setting "False" if not want to receive email
  send_email_when_fail: True # True, False. Setting "False" if not want to receive email
  smtp_server: ap.relay.ibm.com
  sender: jbtang@au1.ibm.com
  receivers: ['jbtang@au1.ibm.com', 'bennytang2008@gmail.com']


